
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbmeqiwnnusbvcfirfuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpibWVxaXdubnVzYnZjZmlyZnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTA1NjUsImV4cCI6MjA2MTgyNjU2NX0.bnnUGDXuSZFoUepP2QYhjWtPN0pHK57i2-NaLZ8WLe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true
    },
    global: {
      headers: {
        'X-Client-Info': 'lovable-portfolio-app'
      }
    }
  }
);
